#!/usr/bin/env python3

from werkzeug.serving import run_simple

from pabu.app import wsgi_application

run_simple(
    '0.0.0.0',
    5000,
    wsgi_application,
    use_reloader = True,
    use_debugger = True,
    extra_files = ['pabu.yaml', 'pabu/templates/index.html']
)
