"""sources

Revision ID: 00e9316c78f4
Revises: e1c315078dc3
Create Date: 2019-05-01 16:44:05.744545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e9316c78f4'
down_revision = 'e1c315078dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('sources', sa.Column('receive_token', sa.String(), nullable=False))
    op.drop_constraint('sources_user_id_fkey', 'sources', type_='foreignkey')
    op.create_foreign_key('sources_project_id_fkey', 'sources', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sources', 'user_id')
    op.alter_column('sources', 'type', type_ = sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('sources_project_id_fkey', 'sources', type_='foreignkey')
    op.create_foreign_key('sources_user_id_fkey', 'sources', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sources', 'receive_token')
    op.drop_column('sources', 'project_id')
    # ### end Alembic commands ###
