"""project_users table rename

Revision ID: 4d15a831ea33
Revises: 401b70052c48
Create Date: 2019-03-09 20:01:23.422831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d15a831ea33'
down_revision = '401b70052c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_users',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('projects_users_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_users_',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='projects_users__project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='projects_users__user_id_fkey')
    )
    op.drop_table('projects_users')
    # ### end Alembic commands ###
